name: twitter-sentiment
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip
  - pandas
  - numpy
  - scikit-learn
  - tqdm
  - jupyter
  - pip:
    - transformers
    - contractions
    - emoji
    - torch
    - pymongo